FROM vllm/vllm-openai:v0.7.3

RUN wget https://github.com/Oxen-AI/Oxen/releases/download/v0.35.0/oxen-ubuntu-22.04.deb && \
    dpkg -i oxen-ubuntu-22.04.deb && \
    rm oxen-ubuntu-22.04.deb


# Verify installation
RUN oxen --version

# Set working directory (optional, but good practice)
WORKDIR /app

# Keep the same entrypoint as the base image
# (vLLM image should already have the correct entrypoint)